server:
  port: 8080

spring:
  application:
    name: ecommerce-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:ecommerce_user}
    password: ${DB_PASSWORD:ecommerce123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

app:
  cors:
     allowed-origins: http://localhost:5173,http://localhost:3000,https://ecommerce-fullstack-2k1bs454y-gowtham-m.vercel.app
  jwt:
    secret: ${JWT_SECRET:replace-this-with-a-long-random-secret-at-least-32-chars-for-hs256}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}   # 24 hours
